### ISSUE TITLE
test.js

### ISSUE THREAD

**Issue by Karyum** [FACN7/aom-tdd-week3#12]
1) there is a lot of commented out code, is this really needed to commented cause it's just dead code.

2) left over console logs, a general good practice is to not have console logs when pushing code to the github because the next person who runs the website or the tests would just get confused on whats going on, it's not a sexy line of code :smile: 

3) MarkTodo function is not tested, the code for the test is commented out

4) in the SortTodo test why do you need to use MarkTodo ? it does not help with the sort in anyway [here is the line of code](https://github.com/FACN7/aom-tdd-week3/blob/master/skeleton/test.js#L113)

**Comment by omriza5** [comment]
done
